import Head from 'next/head';
import NavBar from '../components/NavBar';
import MyChart from '../components/Chart';
import CircleData from '../components/CircleData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Next.js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      

      <NavBar/>
      <main className="bg-[#F4F6F9] px-10 py-4 container mx-auto  mt-1">
        {/* <h1 className="text-4xl font-bold text-center">
          Welcome to Skill Capital
        </h1> */}
        <div class="container mx-auto">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-6">
      {/* <!-- Card 1 --> */}
      <div class="bg-white p-6 rounded-lg shadow-md flex items-center space-x-4">
        <img src='/Group 6.png' class="w-12 h-15"/>
        
        <div>
          <h2 class="text-sm font-light">Not Connected</h2>
          <p class="text-black-800 font-bold">1</p>
        </div>
      </div>
      {/* <!-- Card 2 --> */}
      <div class="bg-white p-6 rounded-lg shadow-md flex items-center space-x-4">
      <img src='/Group 6.png' class="w-12 h-15"/>
        <div>
          <h2 class="text-sm font-light">Warm Lead</h2>
          <p class="text-black-800 font-bold">25</p>
        </div>
      </div>
      {/* <!-- Card 3 --> */}
      <div class="bg-white p-6 rounded-lg shadow-md flex items-center space-x-4">
      <img src='/Group 6.png' class="w-12 h-15"/>
        <div>
          <h2 class="text-sm font-light">Attempted</h2>
          <p class="text-black-800 font-bold">21</p>
        </div>
      </div>
      {/* <!-- Card 4 --> */}
      <div class="bg-white p-6 rounded-lg shadow-md flex items-center space-x-4">
      <img src='/Group 6.png' class="w-12 h-15"/>
        <div>
          <h2 class="text-sm font-light">Registred</h2>
          <p class="text-black-800 font-bold">1</p>
        </div>
      </div>
      {/* <!-- Card 5 --> */}
      <div class="bg-white p-6 rounded-lg shadow-md flex items-center space-x-4">
      <img src='/Group 6.png' class="w-12 h-15"/>
        <div>
          <h2 class="text-sm font-light">Oppurtunity</h2>
          <p class="text-black-800 font-bold">1</p>
        </div>
      </div>
      <div class="bg-white p-6 rounded-lg shadow-md flex items-center space-x-4">
      <img src='/Group 6.png' class="w-12 h-15"/>
        <div>
          <h2 class="text-sm font-light">Cold Lead</h2>
          <p class="text-black-800 font-bold">36</p>
        </div>
      </div>
    </div>
  </div>
  <div className="flex items-center  space-x-16">
  <div className="my-8">
            <MyChart />
          </div>
          <CircleData />
        </div>
      </main>
    </div>
  );
}
